# Generated by Django 4.0.3 on 2023-03-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mylogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('ip_address', models.TextField(max_length=100)),
                ('port', models.TextField(max_length=100)),
                ('http_response', models.TextField(max_length=100)),
            ],
        ),
    ]
