# Generated by Django 4.0.3 on 2023-03-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mylogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField(max_length=100)),
                ('name', models.TextField(max_length=100)),
                ('ip_address', models.TextField(max_length=100)),
                ('massage', models.TextField(max_length=2000)),
            ],
        ),
    ]
